name: sasohae

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: npm install
        run: npm install
        
      - name: Create .env
        shell: bash
        env:
          ENV_VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
        run: |
          touch .env
          echo VUE_APP_BASE_URL="$ENV_VUE_APP_BASE_URL" >> .env
          cat .env

      - name: build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://sasohae.com
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.CDN_DISTRIBUTION_ID}} --paths "/*"
